AllCops:
  Include:
    - '**/Berksfile'
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Metrics/MethodLength:
#   Max: 20

#inherit_from: .rubocop_todo.yml
